<?php

namespace Phenom\WafeeeBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends EntityRepository
{
    public function findShop($id) {
        $em = $this->getEntityManager();
        $query = $em->createQuery(
            'SELECT s.id
            FROM PhenomWafeeeBundle:Category c
            JOIN c.shop_id s
            WHERE c.id='.$id
        );
        return $query->getOneOrNullResult();
    }
}
