<?php

namespace Phenom\WafeeeBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends EntityRepository
{
    public function findAllProductByName($order = 'ASC')
    {
        $em = $this->getEntityManager();
        $query = $em->createQuery('SELECT p FROM PhenomWafeeeBundle:Product p ORDER BY p.name '.$order);
        return $query->getResult();
    }

    public function findProductById($id) {
        $em = $this->getEntityManager();
        $query = $em->createQuery('SELECT p FROM PhenomWafeeeBundle:Product p WHERE p.id='.$id);
        return $query->getOneOrNullResult();
    }

    public function findCategoryId($id) {
        $em = $this->getEntityManager();
        $query = $em->createQuery(
            'SELECT c.id
            FROM PhenomWafeeeBundle:Product p
            JOIN PhenomWafeeeBundle:Category c
            WHERE p.id='.$id
        );
        return $query->getOneOrNullResult();
    }
}
