<?php

namespace Phenom\WafeeeBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ShopFollowRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ShopFollowRepository extends EntityRepository
{
}
