<?php

namespace Phenom\WafeeeBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ShopVotePointRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ShopVotePointRepository extends EntityRepository
{
    public function checkUserRated($idU, $idS) {
        $em = $this->getEntityManager();
        $query = $em->createQuery("");
    }
}
