security:
    providers:
        our_db_provider:
            entity:
                class: PhenomWafeeeBundle:User
                property: username

    encoders:
        Phenom\WafeeeBundle\Entity\User:
            algorithm: bcrypt
            cost: 13

    firewalls:
        default:
            anonymous: ~
            http_basic: ~
    access_control:
        # require ROLE_ADMIN for /admin*
        - { path: ^/admin, roles: ROLE_ADMIN }