security:
    providers:
        our_db_provider:
            entity:
                class: PhenomWafeeeBundle:User
                property: username

    encoders:
        Phenom\WafeeeBundle\Entity\User:
            algorithm: bcrypt
            cost: 13

    firewalls:
        secured_area:
            anonymous: ~
            http_basic: ~
            form_login:
                login_path: /login
                check_path: /login_check

    access_control:
        # require ROLE_ADMIN for /admin*
        - { path: ^/admin, roles: ROLE_ADMIN }