security:
    providers:
        our_db_provider:
            entity:
                class: PhenomWafeeeBundle:User
                property: username
        my_custom_hwi_provider:
            id: ib_user.oauth_user_provider

    encoders:
        Phenom\WafeeeBundle\Entity\User:
            algorithm: bcrypt
            cost: 13

    role_hierarchy:
        ROLE_ADMIN: ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN]

    firewalls:
        secured_area:
            pattern: ^/.*
#            http_basic: ~
            form_login:
                provider: our_db_provider
                login_path: /login
                check_path: /login_check
#                success_handler: security.authentication.success_handler
                csrf_provider: security.csrf.token_manager
                intention: authenticate
            logout:
                path: /logout
                target: /
#                success_handler: security.authentication.logout_success_handler
            oauth:
                resource_owners:
                    facebook:     "/login/check-facebook"
                login_path:       /login
                failure_path:      /login
                oauth_user_provider:
                    service: ib_user.oauth_user_provider
            anonymous: true
            security: true
            remember_me:
                key: "%secret%"
                lifetime: 604800
                path: /

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        # require ROLE_ADMIN for /admin*
        - { path: ^/admin, roles: ROLE_ADMIN }