security:
    providers:
        our_db_provider:
            entity:
                class: PhenomWafeeeBundle:User
                property: username

    encoders:
        Phenom\WafeeeBundle\Entity\User:
            algorithm: bcrypt
            cost: 13

    firewalls:
        secured_area:
            pattern: ^/.*
#            http_basic: ~
            form_login:
                provider: our_db_provider
                login_path: /login
                check_path: /login_check
                csrf_provider: security.csrf.token_manager
                intention: authenticate
            logout:
                path: /logout
                target: /
            anonymous: true
            security: true
            remember_me:
                key: "%secret%"
                lifetime: 604800
                path: /

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        # require ROLE_ADMIN for /admin*
        - { path: ^/admin, roles: ROLE_ADMIN }